### ISSUE TITLE
Issue with adding Galleries to new adverts.

### ISSUE THREAD

**Issue by numis-ips** [netwaretcs/Classifieds#10]
Trying to add Gallery album to advert when creating, but it doesn't show up in the final when advert published.
![Screenshot_1](https://user-images.githubusercontent.com/83723982/117265687-27ed8080-ae5d-11eb-9334-9262274ab081.png)

**Comment by numis-ips** [comment]
Due to another bug with Amazon S3, gonna check it for that issue too.

**Comment by numis-ips** [comment]
No, the trouble isn't with storage system. The bug is actual.

**Comment by netwaretcs** [comment]
It seems that this part of the application has never been developed. There is a lot of work to be done, so I am removing the functionality for now.

**Comment by numis-ips** [comment]
Ok, got it

**Comment by netwaretcs** [comment]
Feature removed
