### ISSUE TITLE
Bug with buttons (hiding)

### ISSUE THREAD

**Issue by numis-ips** [netwaretcs/Classifieds#13]
Found bug (hiding) with members store profile buttons. PM button hiding particularly.
![image](https://user-images.githubusercontent.com/83723982/117991533-d0f91700-b346-11eb-9932-dc54f0d76abc.png)
![image](https://user-images.githubusercontent.com/83723982/117991573-d9515200-b346-11eb-917b-fe6733b4963c.png)
And how it should be:
![image](https://user-images.githubusercontent.com/83723982/117991609-e3735080-b346-11eb-9dae-4e43051400ae.png)

**Comment by netwaretcs** [comment]
@numis-ips can you confirm this also with default theme?

**Comment by numis-ips** [comment]
Yes, buttons are full hided: 
![image](https://user-images.githubusercontent.com/83723982/119009790-28793180-b99c-11eb-9303-17ea33a373f3.png)

By click on field:
![image](https://user-images.githubusercontent.com/83723982/119010226-80b03380-b99c-11eb-8158-1f87ed828488.png)

Original member profile:
![image](https://user-images.githubusercontent.com/83723982/119010372-a9382d80-b99c-11eb-9726-39b3dcf3cb52.png)

**Comment by numis-ips** [comment]
Same issue for Taman's theme but with another member profile, also size of buttons are different. Looks like it depends on the presence of the store name in the header. 
![image](https://user-images.githubusercontent.com/83723982/119012756-fddca800-b99e-11eb-88c2-0b9e0a7af719.png)
![image](https://user-images.githubusercontent.com/83723982/119012956-2d8bb000-b99f-11eb-8024-242391277a0b.png)
![image](https://user-images.githubusercontent.com/83723982/119013075-4f853280-b99f-11eb-8aa4-69a1bd4103ad.png)
