### ISSUE TITLE
Currencies with no specified amount should not show on "Show Prices In"

### ISSUE THREAD

**Issue by rally-team-tribe** [netwaretcs/Classifieds#15]
We can see that If a currency is selected in the "Show Prices in" and if that currency has no price setting on it, it will only show the "NO VALUE SPECIFIED" since there was no price specified for that certain currency.

This is confusing so is there a way so that if a particular currency was not set, then it should not show in the "Show Prices in"

**Comment by netwaretcs** [comment]
I don't think this can be done, I'll check how invision works in the shop.

**Comment by netwaretcs** [comment]
Just tested 
![Schermata 2021-05-20 alle 10 12 04](https://user-images.githubusercontent.com/67137992/118943359-d57b8c00-b953-11eb-88ba-12f9efc5c800.png)

This is something you need to ask to IPS because Classifieds use the same code to switch currencies.
