### ISSUE TITLE
Since 2.2.2, unable to place ads

### ISSUE THREAD

**Issue by irishrailwaymodels** [netwaretcs/Classifieds#27]
`UPDATE `classifieds_adverts` classifieds_adverts  SET `cl_a_title`='Test Ad',`cl_a_title_seo`='test-ad',`cl_a_content`='<p>
	Please ignore
</p>
',`cl_a_items`=1,`cl_a_price`='{"EUR":{"amount":"55","currency":"EUR"}}',`cl_a_EUR`=(IPS\Math\Number::__set_state(array(
   'positive' => true,
   'beforeDecimalPoint' => 55,
   'numberOfDecimalPlaces' => 0,
   'afterDecimalPoint' => 0,
))),`cl_a_location`='{"lat":1.3733329999999999149196128200856037437915802001953125,"long":32.29027500000000117097442853264510631561279296875,"addressLines":[null],"city":"","region":"","country":"UG","postalCode":""}',`cl_a_url_external_advert`=NULL,`cl_a_contact`=NULL,`cl_a_contact_email`=0,`cl_a_contact_email_email`=NULL,`cl_a_contact_pm`=true,`cl_a_type`='1',`cl_a_condition`='3',`cl_a_package`='2',`cl_a_gallery_album`=NULL WHERE cl_a_id=45 
IPS\Db\Exception: Column 'cl_a_gallery_album' cannot be null (1048)
#0 /home/irishrailwaymod/public_html/system/Db/Db.php(1161): IPS\_Db->preparedQuery('/*irishrailwaym...', Array)
#1 /home/irishrailwaymod/public_html/system/Patterns/ActiveRecord.php(520): IPS\_Db->update('`classifieds_ad...', '`cl_a_title`=?,...', 'WHERE cl_a_id=?')
#2 /home/irishrailwaymod/public_html/applications/classifieds/sources/Advert/Advert.php(1137): IPS\Patterns\_ActiveRecord->save()
#3 /home/irishrailwaymod/public_html/system/Content/Item.php(397): IPS\classifieds\_Advert->processForm(Array)
#4 /home/irishrailwaymod/public_html/applications/classifieds/sources/Advert/Advert.php(1974): IPS\Content\_Item::createFromForm(Array, Object(IPS\classifieds\Category), false)
#5 /home/irishrailwaymod/public_html/applications/classifieds/modules/front/classifieds/submit.php(163): IPS\classifieds\_Advert::createFromForm(Array, Object(IPS\classifieds\Category), false)
#6 /home/irishrailwaymod/public_html/system/Dispatcher/Controller.php(90): IPS\classifieds\modules\front\classifieds\_submit->submit()
#7 /home/irishrailwaymod/public_html/applications/classifieds/modules/front/classifieds/submit.php(28): IPS\Dispatcher\_Controller->execute()
#8 /home/irishrailwaymod/public_html/system/Dispatcher/Dispatcher.php(152): IPS\classifieds\modules\front\classifieds\_submit->execute()
#9 /home/irishrailwaymod/public_html/index.php(13): IPS\_Dispatcher->run()
#10 {main}`

`#0 /home/irishrailwaymod/public_html/init.php(995): IPS\_Log::log('UPDATE `classif...', 'uncaught_except...')
#1 [internal function]: IPS\IPS::exceptionHandler(Object(IPS\Db\Exception))
#2 {main}`

**Comment by irishrailwaymodels** [comment]
[[Template classifieds/front/global/searchResultAdvertSnippet is throwing an error. This theme may be out of date. Run the support tool in the AdminCP to restore the default theme.]]

**Comment by irishrailwaymodels** [comment]
(Have run support tool and everything is up to date_

**Comment by numis-ips** [comment]
> (Have run support tool and everything is up to date_

https://invisioncommunity.com/forums/topic/432540-classifieds-system/?do=findComment&comment=2856105

**Comment by irishrailwaymodels** [comment]
Resolved - thank you very much!

**Comment by netwaretcs** [comment]
Fixed in next release.
