### ISSUE TITLE
Typo in menu manager

### ISSUE THREAD

**Issue by netwaretcs** [netwaretcs/Classifieds#3]
In the Classifieds Menu Manager, there is an error in the spelling of "Wish List". Is there anyway that i can change the names of "Classifieds", "Wishlists", "My Adverts", "My Offers", etc?

**Comment by numis-ips** [comment]
Names can be edited as language translation as you want. 
![image](https://user-images.githubusercontent.com/83723982/117277346-76ece300-ae68-11eb-82d9-312cdc30d8d4.png)
![image](https://user-images.githubusercontent.com/83723982/117277443-8e2bd080-ae68-11eb-9d88-82169cb15438.png)
![image](https://user-images.githubusercontent.com/83723982/117277539-a7348180-ae68-11eb-942b-ca5f53d0eb2c.png)
As for me thats enough.
