### ISSUE TITLE
missing PACKAGE INFO, TYPE or ITEM CONDITION

### ISSUE THREAD

**Issue by AGdrive** [netwaretcs/Classifieds#37]
Hello! 
Trying to submit an advert and see this
You cannot create adverts in this category: missing PACKAGE INFO, TYPE or ITEM CONDITION. If you have already created them, edit your category and choose which ones the category will use. Contact the system administrator.

What does it mean ?

**Comment by waldyrreinoso** [comment]
Yes. I too!!

**Comment by waldyrreinoso** [comment]
I found. You have to create all categories and select.

**Comment by chadlittle** [comment]
I am also having this issue, but I have created these and assigned them to all my categories. Nothing works. Software is unusable to me.

**Comment by chadlittle** [comment]
More specifically, it appears all three fields (package, type, condition) are REQUIRED and MUST be enabled for every category. You cannot leave out say Packages, which I have no use for, or even leave it unselected when editing the category. These limits are confusing enough that I can't see forcing my users to also be confused by these when forum threads work perfectly fine.

**Comment by gkettell** [comment]
I agree, package info, type, and condition should not be required. If they aren't set for a category, leave them off the form. Resorting to maybe writing a hook for this app to get around this.

**Comment by netwaretcs** [comment]
This is not a bug. 
You had to select package, type and condition for every categories you create.
