### ISSUE TITLE
template_error in php 8

### ISSUE THREAD

**Issue by kaldata2** [netwaretcs/Classifieds#38]
TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /uploads/content_templates/template_4_4948644655a4cf87d4133c69fd3380dc_browse.php:3744
Stack trace:
#0 /uploads/content_templates/template_4_4948644655a4cf87d4133c69fd3380dc_browse.php(3744): method_exists()
#1 /system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_classifieds_front_browse->subcategoryRow()
#2 /uploads/content_templates/template_4_4948644655a4cf87d4133c69fd3380dc_browse.php(740): IPS\Theme\_SandboxedTemplate->__call()
#3 /system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_classifieds_front_browse->category()
#4 /applications/classifieds/modules/front/classifieds/browse.php(250): IPS\Theme\_SandboxedTemplate->__call()
#5 /applications/classifieds/modules/front/classifieds/browse.php(41): IPS\classifieds\modules\front\classifieds\_browse->_category()
#6 /system/Dispatcher/Controller.php(101): IPS\classifieds\modules\front\classifieds\_browse->manage()
#7 /applications/classifieds/modules/front/classifieds/browse.php(21): IPS\Dispatcher\_Controller->execute()
#8 /system/Dispatcher/Dispatcher.php(153): IPS\classifieds\modules\front\classifieds\_browse->execute()
#9 /index.php(13): IPS\_Dispatcher->run()
#10 {main}

**Comment by omriamos** [comment]
+1
In addition to a ton of template errors in the IPS system log, there are also many template errors on the frontend, mainly from sub categories display, some of which I had to manually fix hard-coded on my server in order for the system to basically function again.

**Comment by netwaretcs** [comment]
Can you be more precise? What version of the app are you using?

**Comment by kaldata2** [comment]
A year and two months later??? I don't even remember writing here :D
