### ISSUE TITLE
Image missing in wishlist, My offers...

### ISSUE THREAD

**Issue by netwaretcs** [netwaretcs/Classifieds#6]
Image thumbnails are missing for Whishlist, My offers and My renewals:

**Comment by netwaretcs** [comment]
![Schermata 2021-05-03 alle 16 41 31](https://user-images.githubusercontent.com/67137992/116891086-9993b780-ac2e-11eb-8dd5-35dc736740e3.png)

I can't replicate this.

**Comment by netwaretcs** [comment]
I can't replicate this issue. 
Are you on IPS cloud?

**Comment by numis-ips** [comment]
Hi! No, I'm not on IPS cloud - On-premise, but I'm using Amazon s3 as file storage. Maybe it's the trouble.
![Screenshot_1](https://user-images.githubusercontent.com/83723982/117190277-e373cd80-ade7-11eb-9fac-d8ce4d9404c6.png)

**Comment by numis-ips** [comment]
Yes, there is no problem with classic file storage system
![image](https://user-images.githubusercontent.com/83723982/117274081-638c4880-ae65-11eb-8ba4-046b904a0775.png)

**Comment by netwaretcs** [comment]
I'll try to have a look but I don't have a chance to test because I don't have the amazon service.
